Part 20 Simpler
Savelov-Vitaliy/simpler pull request #1
Opened 2018-11-17 18:33 UTC by Savelov-Vitaliy

2018-11-17 21:19 UTC, iBublik requested changes

2018-11-17 21:19 UTC, iBublik commented on app/controllers/tests_controller.rb
> +  def test
?

2018-11-17 21:19 UTC, iBublik commented on app/views/tests/list.html.erb
> +    <p>params: <%= @params %></p>
Зачем этот шаблон, если экшн `list` служит для plain ответа?

2018-11-17 21:19 UTC, iBublik commented on lib/simpler.rb
> +class Object
Не надо манкипатчить дефолтные классы Ruby. Так ты привносишь поведение, нужное только тебе, всем пользователям фреймворка. Я рекомендую создать какой-нибудь класс/модуль Utils, либо использовать [refinements](http://timelessrepo.com/refinements-in-ruby)

2018-11-17 21:19 UTC, iBublik commented on lib/simpler/application.rb
> +      rescue NoMethodError
Вместо отлова ошибки просто верни response_404, если в route оказался nil

2018-11-17 21:19 UTC, iBublik commented on lib/simpler/controller.rb
> +      id = @request.env['PATH_INFO'].match(/\d.*$/)
Во-первых, это явно не задача контроллера. Парсинг параметров маршрута логично сделать в роутере.
Во-вторых, не нужно жестко завязываться на id. Подставляться должен любой именованный параметр, вовсе не обязательно что там число (`tests/:test_title/questions/:id` => `params[:test_title], params[:id]`)
В-третих, контроллер должен иметь доступ как к параметрам маршрута, так и к параметрам формы, к query string параметрам

2018-11-17 21:19 UTC, iBublik commented on lib/simpler/controller.rb
>        set_default_headers
Дефолтные хедеры устанавливают Content-Type, который не всегда соответсвует формату

2018-11-17 21:19 UTC, iBublik commented on lib/simpler/controller/headers.rb
> +    class Headers
Не очень полезный класс получился, вполне без него можно

2018-11-17 21:19 UTC, iBublik commented on log/app.log
> +I, [2018-11-17T23:28:30.289246 #9690]  INFO -- : Request: GET /tests?category=Backend
Лог надо исключить из репозитория

2018-11-17 21:19 UTC, iBublik commented on middleware/logger.rb
> +    @status, @headers, @body = @app.call(env)
Не очень хорошо, что после вызова `call` объект остается "грязным" - в нем лежат артефакты предыдущего вызова (инстанс-переменные)

2018-11-17 21:19 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['handler'] = "#{self.class.name}##{action}"
Это зачем? Ты ведь уже хранишь и контроллер, и экшн

2018-11-17 21:19 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['template'] = View.new(@request.env).template
То, что записывается твоим приложением, лучше как-то помечать (у всех ключей есть префикс `simpler`)

2018-11-17 21:19 UTC, iBublik commented on middleware/logger.rb
> +    @logger.info("Parameters: #{@request.params}")
Здесь должны быть все параметры - и маршрута, и формы, и query string

2018-11-17 21:19 UTC, iBublik commented on middleware/logger.rb
> +    @logger.info("Response: #{@status} [#{@headers['Content-Type']}] #{@request.fetch_header('template')}")
Странно, что заголовки ты по-разному получаешь - где-то из headers, где-то из request

2018-11-19 07:13 UTC, Savelov-Vitaliy commented on app/controllers/tests_controller.rb
> +  def test
Выводит тестовые данные. Удалить?

2018-11-19 07:14 UTC, Savelov-Vitaliy commented on app/controllers/tests_controller.rb
> +  def test
удалил

2018-11-19 07:28 UTC, Savelov-Vitaliy commented on app/views/tests/list.html.erb
> +    <p>params: <%= @params %></p>
Вопрос, наверное, не про за чем этот шаблон, а почему этот шаблон такой?
- шаблоны автоматически назначаются если в ClassController#action нет render plain '\<text\>', несмотря на то какой headers['Content-Type'] указан, 'text/plain' или 'text/html'
- удалил html теги из этого шаблона, оставил только текст

2018-11-19 09:03 UTC, Savelov-Vitaliy commented on lib/simpler.rb
> +class Object
круто

2018-11-19 12:12 UTC, Savelov-Vitaliy commented on middleware/logger.rb
> +    @logger.info("Response: #{@status} [#{@headers['Content-Type']}] #{@request.fetch_header('template')}")
Странно, что: request.get_header('Content-Type') 
nil

Но: request.get_header('HTTP_ACCEPT')
"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"

Хотя в контроллере указал что: headers['Content-Type'] = 'text/plain'

Не понятно

2018-11-21 19:26 UTC, iBublik requested changes

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/application.rb
> +      controller.params.update( route.params(env) )
А почему этим занимается Application? Почему контроллер сразу не может вернуть из `params` все параметры?

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/controller.rb
> +      @headers = Hash.new
`@headers = {}`

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/controller.rb
> +      @params = request_params
Удобнее это сделать методом, а не переменной. Он ведь собирает данные из нескольких мест

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/controller.rb
> +      @params.map{|k, v| @request.update_param(k.to_s, v) }
Это зачем? Не нужно мутировать объект запроса, ты так не разберешь что реально с клиента пришло, а что твое приложение натворило

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.params.each.with_object({}){|p, h| h[p[0].to_sym] = p[1]}
С таким названием аргументов вообще не разобрать что происходит
Ключ и значение можно разложить - `{ |(key, value), result| result[key.to_sym] = value }`

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/controller.rb
> +      @response['Content-Type'] = format_render.blank? ? 'text/html' : "text/#{format_render.keys[0]}"
Как-то сложно - вычленять хедер из формата.
Можно устанавливать хедер, когда вызываешь render. А в set_default_headers устанавливать дефолтный Content-Type, если он до этого не был установлен

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/controller.rb
> +      @headers.each{|k, v| @response[k] = v }
Что это?

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/router/route.rb
> +        set_params.each.with_object({}){|p, h|  h[p[1..-1].to_sym] = get_params[set_params.index(p)] if p[0] == ':'}
Код вроде правильный, но из-за непонятных названий аргументов и желания все в одну строку записать понять очень тяжело

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/router/route.rb
> +        reject_params(set) == reject_params(get) and not get[params.last].nil?
Не надо в Ruby использовать `and, or, not`. Поставь rubocop, чтоб он за такое по рукам бил, тогда отучишься :)

2018-11-21 19:26 UTC, iBublik commented on lib/simpler/router/route.rb
> +        reject_params(set) == reject_params(get) and not get[params.last].nil?
Матчинг можно было через регулярку сделать

2018-11-21 19:26 UTC, iBublik commented on middleware/logger.rb
> +    @logger.info("Handler: #{request.get_header('simpler.controller').class.name}##{request.get_header('simpler.action')}")
Упадет, если приложение вернуло 404

2018-11-21 19:26 UTC, iBublik commented on middleware/logger.rb
> +    @logger.info("Parameters: #{request.params}")
У тебя есть инстанс контроллера, у него есть метод, который возвращает _все_ параметры

2018-11-21 19:29 UTC, iBublik commented on middleware/logger.rb
> +    @logger.info("Response: #{@status} [#{@headers['Content-Type']}] #{@request.fetch_header('template')}")
Так ты же заголовок ответа устанавливаешь, а считываешь заголовок запроса

2018-11-22 09:04 UTC, Savelov-Vitaliy commented on middleware/logger.rb
> +    @logger.info("Response: #{@status} [#{@headers['Content-Type']}] #{@request.fetch_header('template')}")
блин, точно! :)))

2018-11-22 15:30 UTC, Savelov-Vitaliy commented on lib/simpler/router/route.rb
> +        reject_params(set) == reject_params(get) and not get[params.last].nil?
Голову сломал, не знаю как с помощью regexp и match() проверить совпадение "/tests/:test_title/questions/:id" и "/tests/1/questions/2"

2018-11-22 15:43 UTC, Savelov-Vitaliy commented on lib/simpler/router/route.rb
> +        set_params.each.with_object({}){|p, h|  h[p[1..-1].to_sym] = get_params[set_params.index(p)] if p[0] == ':'}
Переписал чуть подругому. Постарался сделать код читабельным

2018-11-22 15:53 UTC, Savelov-Vitaliy commented on lib/simpler/controller.rb
> +      @headers.each{|k, v| @response[k] = v }
передаю заголовки в ответ :)))

2018-11-22 16:53 UTC, Savelov-Vitaliy commented on lib/simpler/controller.rb
> +      @headers.each{|k, v| @response[k] = v }
а как иначе передать  в ответ заголовки, установленные в экшене контроллера? 
headers['Header-Name'] = "My header" 

- через доп.класс Headers - плохо
- def headers[]=(header, body) - неверный синтаксис
- могу разве что так: headers 'Header-Name', "My header"

2018-11-22 16:58 UTC, Savelov-Vitaliy commented on lib/simpler/application.rb
> +      controller.params.update( route.params(env) )
В контроллере роут не виден

2018-11-22 17:48 UTC, Savelov-Vitaliy commented on lib/simpler/controller.rb
> +      @headers.each{|k, v| @response[k] = v }
Насколько я понимаю задачу, хедер ['Content-Type'] устанавливается в трех случаях:
1. если в экшене есть присутствует ['Content-Type'] = "my format"
2. если в экшене присутствует render plain: 'Simple text', то headers['Content-Type'] = "text/plain"
3. во всех других случаях, по умолчанию headers['Content-Type'] = "text/html"

2018-11-22 18:13 UTC, Savelov-Vitaliy commented on lib/simpler/controller.rb
> +      @params = request_params
Как в контроллере вытащить параметры из роута?! 
Контроллер ничего не знает про роут!

2018-11-22 18:25 UTC, Savelov-Vitaliy commented on middleware/logger.rb
> +    @logger.info("Response: #{@status} [#{@headers['Content-Type']}] #{@request.fetch_header('template')}")
в логере:  request.get_header('Content-Type') = nil

2018-11-22 18:34 UTC, Savelov-Vitaliy commented on middleware/logger.rb
> +    @logger.info("Response: #{@status} [#{@headers['Content-Type']}] #{@request.fetch_header('template')}")
Я наверно, что то недопонимаю:

- Rack::Request.new(env) читает environment
- Rack::Response.new.finish изменяет environment
- в middleware можно прочитать уже измененный environment

Где моя ошибка?

2018-11-22 18:37 UTC, Savelov-Vitaliy commented on middleware/logger.rb
> +    @logger.info("Parameters: #{request.params}")
в логере нет инстанса контроллера

2018-11-22 19:22 UTC, Savelov-Vitaliy commented on middleware/logger.rb
> +    @logger.info("Parameters: #{request.params}")
ОК. 
Но, на [ форумах ](http://programmerz.ru/questions/116139/calling-a-controller-action-with-argument-from-rack-middleware-question.html) говорят, что middleware должно взаимодействовать только с окружением запроса, а не пытаться напрямую обращаться к контроллеру.

2018-11-22 19:40 UTC, Savelov-Vitaliy commented on middleware/logger.rb
> +    @logger.info("Handler: #{request.get_header('simpler.controller').class.name}##{request.get_header('simpler.action')}")
Не падает. В лог пишет: Handler: NilClass#
Но, все равно исправил.

2018-11-22 20:34 UTC, iBublik commented on lib/simpler/application.rb
> +      controller.params.update( route.params(env) )
Если роут сматчился, он может записать в env свои параметры. А контроллер уже со всех мест их соберет

2018-11-22 20:34 UTC, iBublik commented on lib/simpler/controller.rb
> +      @params = request_params
Контроллер знает про env

2018-11-22 20:36 UTC, iBublik commented on lib/simpler/controller.rb
> +      @headers.each{|k, v| @response[k] = v }
Ну создай метод set_header(name, value) и устанавливай через него. А то сейчас вообще как-то неочевидно - `set_default_headers` по факту и пишет хедеры в ответ, а без него вообще ничего не работает

2018-11-22 20:59 UTC, iBublik requested changes

2018-11-22 20:59 UTC, iBublik commented on lib/simpler/controller.rb
> +      @response['Content-Type'] = 'text/html'
`@response.headers[...] = ...` нагляднее. Но вообще надо через метод-обертку это делать

2018-11-22 20:59 UTC, iBublik commented on lib/simpler/controller.rb
> +      @headers.each { |k, v| @response[k] = v }
Делай это в методе, который устанавливает хедеры

2018-11-22 20:59 UTC, iBublik commented on lib/simpler/router/route.rb
> +        route_path_parts.each_with_index.with_object({}) do |route_path_part_and_index, params|
`each_with_index` устаревший метод, используй `each.with_index`
Я тебе про скобки для раскладывания параметров рассказывал уже, используй в подобных случаях

2018-11-22 20:59 UTC, iBublik commented on lib/simpler/router/route.rb
> +        return false unless route_path_parts.size == get_path_parts.size
Регуляркой это все делается в одно действие. Замени участки с параметрами на `.*` и будет регулярка для проверки маршрута

2018-11-23 16:11 UTC, Savelov-Vitaliy commented on lib/simpler/router/route.rb
> +        return false unless route_path_parts.size == get_path_parts.size
route = "tests/:id"    
path = "/tests/1/questions/1"  
path.match(/\/tests\/.*/) => true

2018-11-23 16:43 UTC, Savelov-Vitaliy commented on lib/simpler/router/route.rb
> +        route_path_parts.each_with_index.with_object({}) do |route_path_part_and_index, params|
не помню и не могу найти, что за скобки?

2018-11-23 17:06 UTC, Savelov-Vitaliy commented on lib/simpler/controller.rb
> +      @request.params.each.with_object({}){|p, h| h[p[0].to_sym] = p[1]}
оч.круто

2018-11-23 20:21 UTC, iBublik requested changes

2018-11-23 20:21 UTC, iBublik commented on lib/simpler/controller.rb
> +      request_params.merge @request.env['simpler.route'].params(@request.env)
Как-то очень громоздко. Можно либо после матчинга роута записывать параметры в env, либо просто при матчинге мутировать сам роут, записывая в него параметры

2018-11-23 20:21 UTC, iBublik commented on lib/simpler/controller.rb
> +      @headers.each { |header, value| set_header(header, value) }
Не надо переменную `@headers` использовать вообще

2018-11-23 20:21 UTC, iBublik commented on lib/simpler/router/route.rb
> +        path = Rack::Request.new(env).env['PATH_INFO']
И зачем использовать Rack, если ты все равно лезешь в env? Там есть методы path/path_info

2018-11-23 20:21 UTC, iBublik commented on lib/simpler/router/route.rb
> +        path.match(@path.gsub(MATCH_REGEXP) { '.+' }) && path_parts(path).size == path_parts(@path).size
Регулярка сложная получилась. Проще разбить роут на части, и заменить часть если она является параметром (начинается с `:`)

2018-11-25 06:42 UTC, iBublik approved these changes

2018-11-25 06:42 UTC, iBublik commented on lib/simpler/router.rb
> +      @routes.find { |route| env['simpler.route.params'] = route.params(env) if route.match?(method, path) }
Тут достаточно неявно все происходит. В `find` ты изменяешь `env`, но при этом его результатом все равно является маршрут (route). А вот если присвоение по какой-то причине вернет nil/false, то метод всегда будет возвращать nil. Поэтому я рекомендую сначала найти нужный маршрут, а уже потом изменять env:
```ruby
@routes.find { ... }.tap do |result|
  env[...] = Hash(result&.params(env))
end
```

2018-11-25 09:22 UTC, Savelov-Vitaliy commented on lib/simpler/router.rb
> +      @routes.find { |route| env['simpler.route.params'] = route.params(env) if route.match?(method, path) }
Да, точно!

2018-11-25 12:26 UTC, merged